{% set version = "0.10.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggalluvial
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggalluvial_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggalluvial/ggalluvial_{{ version }}.tar.gz
  sha256: 60ec41d05e8d61356de03da66e3f979c34cc9a7b3b41a87c03b1a6824a2c8314

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
    - r-dplyr >=0.7.0
    - r-ggplot2 >=2.2.0
    - r-lazyeval
    - r-rlang
    - r-tidyr >=0.7.0
    - r-tidyselect
  run:
    - r-base
    - r-dplyr >=0.7.0
    - r-ggplot2 >=2.2.0
    - r-lazyeval
    - r-rlang
    - r-tidyr >=0.7.0
    - r-tidyselect

test:
  commands:
    - $R -e "library('ggalluvial')"           # [not win]
    - "\"%R%\" -e \"library('ggalluvial')\""  # [win]

about:
  home: http://corybrunson.github.io/ggalluvial/
  license: GPL-3
  summary: Alluvial diagrams use x-splines, sometimes augmented with stacked histograms, to visualize
    multi-dimensional or repeated-measures data with categorical or ordinal variables.
    They can be viewed as simplified and standardized Sankey diagrams; see Riehmann,
    Hanfler, and Froehlich (2005) <doi:10.1109/INFVIS.2005.1532152> and Rosvall and
    Bergstrom (2010) <doi:10.1371/journal.pone.0008694>. This package provides ggplot2
    layers to produce alluvial diagrams from tidy data.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
    - philip-khor
