travis:
  secure:
    BINSTAR_TOKEN: HvPmw/tddw5epUNM/aFavcbzwBjSMzAOCclgECkpzGJ9qO5fNS2NRH3DQS3Abw4PGjvddBDWsGyKMHV/3f3V4fd9F2BUwHOibv9XItGffX2r4Cp7FjbaoOiJTTj8rGsgfSKIAuB7124cWOHAKWO8waeefjj2cZviQ3RVCdYwSYTxX7zf1tYRMzPV8ytquvsTZ4LFyCfQHXoUW/5dtzAIsmYArUXGGCDtd59paSxzGYlBP4xoZQwH1+ayBvoJsqDQHGqE+ZGmohnF09ZrErK/JJFVKVQW3/vxuCsUgcPp0vPTR0W7TBGwM8JnjXP269pYahss1e7nUxXeU6nijUcWaMhQ/lyDuHmvNvo4jMViGb5snJoHb1msW+vJSe5Je1NRTDjjyEkqmvn9rk+fhYRhw3mmQqDtK1aQ4LnLk6yHj3ZreEi88NK2u80XXqRbI4FzDUj6u8yn6/25dwdVApfLFOi8ZA1uJmUJ5zRKeq1rYWNgKDfUJnvsOtXAPKrJlrlr2ZR/guKvghoPfphhHEGQJdZsFOySuzXvkzY2D0OLTxKllyHUfGL+MjcUPnNIghTd33tSLpRTAKhYA9H81YX1gelVJfMcoq+S6rJDFOgmRWddfraWWPowUInjeLOXfg3N5Zj/In2KPp1h5rlNVYMttTBHvX8gjEYGmYKGt/0wrn8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
